### ISSUE TITLE
Dynamic notebook: Double-clicking on horizontal arrows should not open new tabs

### ISSUE THREAD

**Issue by jlnr** [elementary/granite#221]
* Open enough tabs to make the the left/right arrows appear
* Double-click either arrow

Expected:

* Focus moves two tabs to the left/right

Actual:

* Focus moves by one tab, then a new tab is opened (at least in Files and Code)

Maybe this is also what causes https://github.com/elementary/code/issues/485 (which I can also reproduce in Files): All double-clicks, even on arrows/even with the middle mouse button, are interpreted as a "open new tab" gesture?

**Comment by andreasfelix** [comment]
I think the double click on the left/right arrows opens a new tab because the `button_press_event` gets handled by the `DynamicNotebook` class:
```vala
button_press_event.connect ((e) => {
    if (e.type == Gdk.EventType.2BUTTON_PRESS && e.button == 1) { // <-- double click opens new tab!
        new_tab_requested ();
    } else if (e.button == 2 && allow_restoring) {
        restore_last_tab ();
        return true;
    } else if (e.button == 3) {
        menu.popup_at_pointer (e);
    }

    return false;
});
```

I think the `left/right-arrow` buttons have to consume the `button_press_event` explicitly, similar to the `add_button` (the button with the + symbol which creates new tabs):
```vala
add_button.button_press_event.connect ((e) => {
    // Consume double-clicks
    return e.type == Gdk.EventType.2BUTTON_PRESS && e.button == 1;
});
```
These lines prevent the creation of a new tab when double clicking the `add_button`. So I think a similar line is needed for the `left/right arrow` buttons. Unfortunately I can't find the declaration of these buttons in the `DynamicNotebook.vala` file ...

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
