### ISSUE TITLE
Some settings pane titles are not selectable

### ISSUE THREAD

**Issue by D0J0P** [elementary/granite#309]
From [#308](https://github.com/elementary/granite/issues/308). Settings pane titles are selectable so that the user can copy and paste them for convenience, but Notifications, Network, and Sharing pane titles don't seem to be selectable like the other ones.

**Comment by peteruithoven** [comment]
Good point. I think not all plugs use that same AbstractSimpleSettingsPage widget. Could you open up issues in the specific plugs? 
For example the code for the Notifications plug: 
https://github.com/elementary/switchboard-plug-notifications/blob/master/src/Widgets/SettingsHeader.vala

I'll close this issue because I don't think we can do anything on Granite's end.
