### ISSUE TITLE
Deprecate Granite.Services.Settings

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#330]
It's unclear that it actually offers any advantage over GLib.Settings

**Comment by donadigo** [comment]
I'm really not sure if we should do this. GLib.Settings work well and Granite ones don't provide any "additional" functionality but for large setting branches where you have a lot of keys, this class really reduces the burden to maintain all the keys. It is also easy to add new keys because of native Vala syntax.

Just take a look at e.g: https://github.com/elementary/gala/blob/master/src/Settings.vala. This is a lot simpler and cleaner than instantiating random `Setting`'s everywhere in the code.

**Comment by Alecaddd** [comment]
I agree with @donadigo.
The Granite.Services.Settings are an amazingly helpful interface that simplifies handling many keys in one file.
Is this deprecation still under consideration or it's already happening?
Also, what would be the proper approach when handling big settings like the one shared in the previous comment?
Cheers

**Comment by danrabbit** [comment]
I'm not sure what you mean by "this class really reduces the burden to maintain all the keys". Can you explain?

So far from what I've seen, Granite.Services.Settings is sometimes taking hundreds more lines of code than using GLib.Settings and the only thing it seems to do is let you write `settings.key = foo` instead of `settings.set_string ("key", foo)`.

Is there a reason it wouldn't work to have a Settings class that uses GLib.Settings instead of Granite.Services.Settings? I've been using a single static instance in the application class so that you can do something like `Foo.Application.settings`. I agree instantiating a new GLib.Settings in every class doesn't really make sense.

**Comment by benwaffle** [comment]
Does anyone use it for property binding? https://valadoc.org/gobject-2.0/GLib.Binding.html

**Comment by danrabbit** [comment]
GLib.Settings has binding built in: https://valadoc.org/gio-2.0/GLib.Settings.bind.html

**Comment by baturax** [comment]
will docs be updated?
