### ISSUE TITLE
Marquee contents of OverlayBar instead of ellipsizing

### ISSUE THREAD

**Issue by yozachar** [elementary/granite#409]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
When file names get longer the info bar is also elongated, even to the point of filling out the full bottom.

![Screenshot from 2020-06-05 23 07 47](https://user-images.githubusercontent.com/38415384/83907497-1f8b5200-a783-11ea-80dd-b50a0d56d7bf.png)

**Describe the solution you'd like**
So instead of simply truncating, let the text scroll from right to left if it is long.

**Comment by joe733** [comment]
I came up with this idea.

Instead of marquee whole content of the OverlayBar, my suggestion is just to scroll the name (the contents just within the orange box). Possible? The size and directory structure does not marqee along.

![image](https://user-images.githubusercontent.com/38415384/84848079-1a29e380-b070-11ea-9a96-f16c4692de7b.png)

And btw should `filetype / folder` be explicitly mentioned?

**Comment by yozachar** [comment]
Closing, outdated.
