### ISSUE TITLE
Chrome prev-next to close of Close button GTK.Window

### ISSUE THREAD

**Issue by BellemareMederic** [elementary/granite#433]
## Prerequisites
- Google Chrome

## OS information
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera
Kernel: 4.15.0-121-generic

## Feature
I dont know if im in the good repo for this issue please said to me if im not. i dont know if its a Feature or juste Issue but i think GTK window close position need to be re-think. i work on my laptop and when i try to get back from one page in Google Chrome i close the application litteraly because a miss click .... or do you know if its possible for Chrome to move this arrow anywhere else ?

thanks for all your work people this OS is amazing !

**Additional context**

![image](https://user-images.githubusercontent.com/6710664/96286145-ef17b800-0fad-11eb-9319-991448e44da9.png)

**Comment by danrabbit** [comment]
There's unfortunately nothing we can do at elementary to change the design of Google Chrome. This is a completely non-native app that draws its own window decorations and controls. You'll need to file an issue with Google wherever they accept feedback.

Closing this issue as "Out of scope" because this is an issue with the Google Chrome codebase and there's nothing that can be done within the scope of elementary's power about this
